version: "3"

services:

  ps_db:
    image: mysql:5.7
    container_name: ps_db
    env_file: .env

  ps_web:
    image: prestashop/prestashop:1.7-apache
    container_name: ps_web
    env_file: .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ../../..:/var/www/html/modules/ps_banner
    ports:
      - 80:80

networks:
  ps-net:
