<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTz2muqx\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTz2muqx/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerTz2muqx.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerTz2muqx\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerTz2muqx\appDevDebugProjectContainer([
    'container.build_hash' => 'Tz2muqx',
    'container.build_id' => '1bdf226a',
    'container.build_time' => 1702507490,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTz2muqx');
