<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQstous2\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQstous2/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerQstous2.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerQstous2\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerQstous2\appDevDebugProjectContainer([
    'container.build_hash' => 'Qstous2',
    'container.build_id' => 'c29e7685',
    'container.build_time' => 1701462107,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQstous2');
