<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerP5tmmcw\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerP5tmmcw/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerP5tmmcw.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerP5tmmcw\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerP5tmmcw\appDevDebugProjectContainer([
    'container.build_hash' => 'P5tmmcw',
    'container.build_id' => 'f6dab683',
    'container.build_time' => 1701372622,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerP5tmmcw');
