name: Cron Update JS Routing
on:
    schedule:
        - cron:  '0 23 * * *'
jobs:
  js-routing-dump:
    runs-on: ubuntu-latest
    name: Update JS Routing
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: mbstring, intl, gd, xml, dom, json, fileinfo, curl, zip, iconv, simplexml

      - name: Setup MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: '8.0'
          mysql database: 'prestashop'
          mysql root password: 'password'

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'npm'
          cache-dependency-path: |
            admin-dev/**/package-lock.json
            tests/**/package-lock.json
            themes/**/package-lock.json

      - name: Setup NPM
        shell: bash
        run: npm i -g npm@6

      - name: Checkout
        uses: actions/checkout@v3

      - name: PrestaShop Configuration
        run: cp .github/workflows/phpunit/parameters.yml app/config/parameters.yml

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache Composer Directory
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
                 ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install --prefer-dist
      - name: Build assets
        run: make assets

      - name: Change MySQL authentication method
        run: mysql -h127.0.0.1 -uroot -ppassword -e "ALTER USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY 'password'; FLUSH PRIVILEGES;"

      - name: Install PrestaShop
        run: php install-dev/index_cli.php --language=en --country=fr --domain=localhost --db_server=127.0.0.1 --db_password=password --db_name=prestashop --db_create=1 --name=prestashop.unit.test --email=demo@prestashop.com --password=prestashop_demo

      - name: Dump JS Routing file
        run: php bin/console fos:js-routing:dump --format=json --target=admin-dev/themes/new-theme/js/fos_js_routes.json

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            commit-message: Updated JS Routing file
            committer: PrestonBot <noreply@github.com>
            author: prestonBot <prestonBot@users.noreply.github.com>
            title: 'Updated JS Routing file'
            body: |
                    | Questions         | Answers
                    | ----------------- | -------------------------------------------------------
                    | Branch?           | develop
                    | Description?      | Updated JS Routing file
                    | Type?             | improvement
                    | Category?         | CO
                    | BC breaks?        | no
                    | Deprecations?     | no
                    | Fixed ticket?     | N/A
                    | How to test?      | N/A
                    | Possible impacts? | N/A
            base: 'develop'
            delete-branch: true
