name: UI tests - PHP 7.4

on:
  pull_request:
    types: [opened,reopened,synchronize]

jobs:

  sanity:
    runs-on: ubuntu-latest
    name: Sanity - PHP 7.4
    strategy:
      matrix:
        php: [ '7.4' ]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl, gd, xml, dom, json, fileinfo, curl, zip, iconv, simplexml, pdo, mysql

      - name: Setup Apache
        run: sudo bash .github/workflows/sanity/setup-apache.sh ${{ github.workspace }} ${{ matrix.php }}

      - name: Setup MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: '8.0'
          mysql database: 'prestashop'
          mysql root password: 'password'

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'npm'
          cache-dependency-path: |
            admin-dev/**/package-lock.json
            tests/**/package-lock.json
            themes/**/package-lock.json

      - name: Setup NPM
        shell: bash
        run: npm i -g npm@6

      - name: PrestaShop Configuration
        run: cp .github/workflows/phpunit/parameters.yml app/config/parameters.yml

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer Directory
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Composer install and build assets
        run: make

      - run: |
          sudo chown www-data:www-data -R ${{ github.workspace }} && \
          sudo mkdir -p /var/lib/php/sessions && \
          sudo chown www-data:www-data -R /var/lib/php/sessions && \
          sudo service apache2 restart

      - name: Cache Playwright browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright/
          key: ${{ runner.os }}-browsers

      - name: Change MySQL authentication method
        run: mysql -h127.0.0.1 -uroot -ppassword -e "ALTER USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY 'password'; FLUSH PRIVILEGES;"

      - name: Run tests
        run: |
          npm install && npm run test:sanity:fast-fail
        env:
          URL_FO: http://localhost/
          DB_NAME: prestashop
          DB_PASSWD: password
          HEADLESS: true
          TAKE_SCREENSHOT_AFTER_FAIL: true
        working-directory: ./tests/UI

      - uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: screenshots-${{ matrix.php }}
          path: ./tests/UI/screenshots/
